### ISSUE TITLE
[windows] crash on load with System.FormatException: The input string '.5' was not in a correct format. (locale issue?)

### ISSUE THREAD

**Issue by avi-0** [ExOK/Celeste64#1]
```
Celeste 64 v.1.0.0
Error Log (29/1/2024 21:27:32)
Call Stack:
System.AggregateException: One or more errors occurred. (The input string '.5' was not in a correct format.)
 ---> System.FormatException: The input string '.5' was not in a correct format.
   at System.Number.ThrowFormatException[TChar](ReadOnlySpan`1)
   at System.Number.ParseFloat[TChar,TFloat](ReadOnlySpan`1, NumberStyles, NumberFormatInfo)
   at System.Single.Parse(ReadOnlySpan`1, NumberStyles , IFormatProvider )
   at System.Single.Parse(String, NumberStyles, IFormatProvider )
   at System.Single.Parse(String, IFormatProvider )
   at System.Convert.ToSingle(String, IFormatProvider)
   at System.String.System.IConvertible.ToSingle(IFormatProvider)
   at System.Convert.ChangeType(Object, Type , IFormatProvider)
   at System.Convert.ChangeType(Object, Type )
   at Sledge.Formats.Map.Objects.Entity.GetProperty[T](String, T)
   at Sledge.Formats.Map.Objects.Entity.GetFloatProperty(String, Single)
   at Celeste64.Map..ctor(String, String) in C:\Users\thenb\Projects\Celeste64_Dev\Source\Map.cs:line 122
   at Celeste64.Assets.<>c__DisplayClass20_1.<Load>b__0() in C:\Users\thenb\Projects\Celeste64_Dev\Source\Assets.cs:line 76
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__281_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread, ExecutionContext, ContextCallback, Object)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread, ExecutionContext, ContextCallback, Object)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task&, Thread )
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean)
   at System.Threading.Tasks.Task.Wait(Int32, CancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Celeste64.Assets.Load() in C:\Users\thenb\Projects\Celeste64_Dev\Source\Assets.cs:line 181
   at Celeste64.Startup.BeginGame() in C:\Users\thenb\Projects\Celeste64_Dev\Source\Scenes\Startup.cs:line 16
   at Celeste64.Startup.Update() in C:\Users\thenb\Projects\Celeste64_Dev\Source\Scenes\Startup.cs:line 46
   at Celeste64.Game.Update() in C:\Users\thenb\Projects\Celeste64_Dev\Source\Game.cs:line 122
   at Foster.Framework.App.<Tick>g__Update|69_0(TimeSpan)
   at Foster.Framework.App.Tick()
   at Foster.Framework.App.Run(String, Int32, Int32, Boolean )
   at Foster.Framework.App.Run[T](String, Int32, Int32, Boolean )
   at Celeste64.Program.Main(String[]) in C:\Users\thenb\Projects\Celeste64_Dev\Source\Program.cs:line 19
Game Output:
Celeste 64 v.1.0.0
Foster: v0.1.13
Platform: Microsoft Windows 10.0.22621 (X64)
Framework: .NET 8.0.0
SDL: v2.28.5
OpenGL: v3.3.0 NVIDIA 546.26, NVIDIA GeForce GTX 1650/PCIe/SSE2
FMOD Bindings: v20218
FMOD: v20207
Loaded Bank: C:\Users\avi\Downloads\Celeste64-win-x64\Celeste64-win-x64\Content\Audio\Master.strings.bank
Loaded Bank: C:\Users\avi\Downloads\Celeste64-win-x64\Celeste64-win-x64\Content\Audio\Master.bank
Loaded Bank: C:\Users\avi\Downloads\Celeste64-win-x64\Celeste64-win-x64\Content\Audio\music.bank
Loaded Bank: C:\Users\avi\Downloads\Celeste64-win-x64\Celeste64-win-x64\Content\Audio\sfx.bank
```

I believe this might have to do with my PC currently being in a bizarre mixture of English and Spanish settings, with regional formats being set to Spanish (Argentina); I changed that specific setting to English (United States) and the game launches now.

**Comment by NoelFB** [comment]
Thanks, fixing it now.

**Comment by NoelFB** [comment]
Should be fixed with https://github.com/ExOK/Celeste64/commit/be246455e1f14461704ef38a80dc596349b47b3a

**Comment by NoelFB** [comment]
Definitely resolved; Closing for now!
