### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by moude3** [ExOK/Celeste64#28]
I was able to start the game once but without audio. Now I cannot start the game.

Celeste 64 v.1.0.1
Error Log (1/31/2024 7:56:59 AM)
Call Stack:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Celeste64.Audio.LoadBank(String) in /home/noel/Projects/Celeste64/Source/Audio/Audio.cs:line 147
   at Celeste64.Audio.Load(String) in /home/noel/Projects/Celeste64/Source/Audio/Audio.cs:line 127
   at Celeste64.Assets.Load() in /home/noel/Projects/Celeste64/Source/Assets.cs:line 125
   at Celeste64.Startup.BeginGame() in /home/noel/Projects/Celeste64/Source/Scenes/Startup.cs:line 16
   at Celeste64.Startup.Update() in /home/noel/Projects/Celeste64/Source/Scenes/Startup.cs:line 46
   at Celeste64.Game.Update() in /home/noel/Projects/Celeste64/Source/Game.cs:line 123
   at Foster.Framework.App.<Tick>g__Update|69_0(TimeSpan)
   at Foster.Framework.App.Tick()
   at Foster.Framework.App.Run(String, Int32, Int32, Boolean )
   at Foster.Framework.App.Run[T](String, Int32, Int32, Boolean )
   at Celeste64.Program.Main(String[]) in /home/noel/Projects/Celeste64/Source/Program.cs:line 23
Game Output:
Celeste 64 v.1.0.1
Foster: v0.1.14
Platform: Microsoft Windows 10.0.22631 (X64)   ---im using win 11---
Framework: .NET 8.0.1
SDL: v2.28.5
OpenGL: v3.3.0 NVIDIA 546.17, NVIDIA GeForce RTX 3070 Ti/PCIe/SSE2
FMOD Bindings: v20218
FMOD: v20207
Loaded Bank: E:\Celeste64-win-x64\Content\Audio\Master.strings.bank

**Comment by steviegt6** [comment]
Try reinstalling; corrupted file, maybe? Or improper file permissions?

**Comment by moude3** [comment]
Reinstalled and it ran just fine. Odd since I did reinstall it earlier but didn't work. Closing issue, Sorry for redundant thread.

**Comment by SnipUndercover** [comment]
While investigating the issue I noticed all `Audio.Check` does is call `Debug.Assert`, which doesn't get captured in `Log.Logs` (plus, I believe the game is compiled in Release mode), nor does it actually fail fast.
https://github.com/ExOK/Celeste64/blob/76408be55a0d5338f74cea130d1984643dae50fb/Source/Audio/Audio.cs#L296-L297

**Comment by NoelFB** [comment]
Yeah we should maybe change that to at least log... possibly just throw an exception too.
